### ISSUE TITLE
addWebpackAlias with typescript doesn't work

### ISSUE THREAD

**Issue by junhwong** [arackaf/customize-cra#250]
config-overrides.js
```js
...
module.exports = override(
addWebpackAlias({
        '@': path.resolve(__dirname, 'src')
    }),
)
```

App.tsx
```
import { Pagination } from '@/components/Pagination';
```

and error:
```
TypeScript error in /home/devshost/tmp/my-app/src/App.tsx(6,28):
Cannot find module '@/components/Pagination'.  TS2307

    4 | import { Button } from 'antd';
    5 | 
  > 6 | import { Pagination } from '@/components/Pagination';
      |                            ^
    7 | 
    8 | function App() {
    9 |   return (
```

Tring add `compilerOptions/paths` to tsconfig.json, IDE(VSCODE) looks OK, but run(npm start) `paths`  field  lost. Get the error above again！

**Comment by junhwong** [comment]
![image](https://user-images.githubusercontent.com/8044424/82125189-ec365280-97d6-11ea-8b17-285c23fab85e.png)
![image](https://user-images.githubusercontent.com/8044424/82125211-053f0380-97d7-11ea-8619-6c51d0917764.png)

**Comment by zhouyu1993** [comment]
I have the same problem

**Comment by junhwong** [comment]
And Jest doesn't work，see more:
```
FAIL  src/App.test.tsx
  ● Test suite failed to run

    Cannot find module '@/assets/logo.svg' from 'App.tsx'

    However, Jest was able to find:
        './App.less'
        './App.test.tsx'
        './App.tsx'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

       5 | // import { Pagination } from './components/Pagination';
       6 | import { SideMenu } from './Menu'
    >  7 | import logo from '@/assets/logo.svg';
         | ^
       8 | import './App.less';
       9 | 
      10 | // import { BaseView } from './layouts/Basic'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (src/App.tsx:7:1)

Test Suites: 1 failed, 1 total
```

**Comment by davidmwhynot** [comment]
I am having this exact issue right now, and attempting to find a similar solution. I find it frustrating that create-react-app works so poorly with extremely common tools like jest and TypeScript.

**Comment by davidmwhynot** [comment]
I ended up using [craco-alias](https://github.com/risenforces/craco-alias) instead.

**Comment by junhwong** [comment]
@davidmwhynot craco-alias  yes,tks!
