### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by lhb11** [arackaf/customize-cra#267]
![image](https://user-images.githubusercontent.com/15186545/92581039-bce5ad00-f2c1-11ea-85a1-9540cb6c3323.png)

C:\Users\oe_lihongbin\Desktop\investment\node_modules\customize-cra\dist\index.cjs.js:1
"use strict";function _interopDefault(e){return e&&"object"==typeof e&&"default"in e?e.default:e}Object.defineProperty(exports,"__esModule",{value:!0});var flow=_interopDefault(require("lodash.flow"));function _defineProperty(e,s,t){return s in e?Object.defineProperty(e,s,{value:t,enumerable:!0,configurable:!0,writable:!0}):e[s]=t,e}function _objectSpread2(e){for(var s=1;s<arguments.length;s++)if(s%2){var t=null!=arguments[s]?arguments[s]:{},r=Object.keys(t);"function"==typeof Object.getOwnPropertySymbols&&(r=r.concat(Object.getOwnPropertySymbols(t).filter(function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable}))),r.forEach(function(s){_defineProperty(e,s,t[s])})}else Object.defineProperties(e,Object.getOwnPropertyDescriptors(arguments[s]));return e}const getBabelLoader=(e,s)=>{let t;t=s?e=>e.loader&&e.loader.includes("babel")&&e.exclude:e=>e.loader&&e.loader.includes("babel")&&e.include;let r=e.module.rules.

TypeError: Cannot read property 'push' of undefined
    at Object.<anonymous> (C:\Users\oe_lihongbin\Desktop\investment\node_modules\customize-cra\dist\index.cjs.js:1:5679)
    at Object.webpack (C:\Users\oe_lihongbin\Desktop\investment\node_modules\lodash.flow\index.js:177:42)
    at Object.<anonymous> (C:\Users\oe_lihongbin\Desktop\investment\node_modules\react-app-rewired\scripts\start.js:29:15)

不确认是哪里类型不对

**Comment by francisco4challenge** [comment]
Any feedback on this?
