### ISSUE TITLE
Erro on test

### ISSUE THREAD

**Issue by max10rogerio** [arackaf/customize-cra#94]
Tests broken when used `addWebpackAlias`.

My configs:
```js
const { override, addWebpackAlias } = require('customize-cra')
const path = require('path')
const resolve = str => path.resolve(__dirname, str)

module.exports = override(addWebpackAlias({
  'Root': resolve('./'),
  'Public': resolve('public'),
  'Src': resolve('src'),
  'Api': resolve('src/api'),
  'Assets': resolve('src/assets'),
  'Components': resolve('src/components'),
  'Containers': resolve('src/containers'),
  'Config': resolve('src/config'),
  'Router': resolve('src/router'),
  'Utils': resolve('src/utils')
}))
```

This is my error:
```
 FAIL  src/containers/Perfil/components/FormEndereco.test.js
  ● Test suite failed to run

    Cannot find module 'Components/Inputs/Masked/CEP' from 'FormEndereco.js'

      10 | import CircularProgress from '@material-ui/core/CircularProgress'
      11 | 
    > 12 | import CEPMask from 'Components/Inputs/Masked/CEP'
         | ^
      13 | 
      14 | const FormEndereco = ({ handleCep, ...props }) => (
      15 |   <div className={props.classes.containerPaper}>

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (src/containers/Perfil/components/FormEndereco.js:12:1)
```

But the alias work in development and production.

**PS:** Apparently, the jest not replace the alias to full path

**Comment by FezVrasta** [comment]
You need to set the aliases in Jest separately.

**Comment by max10rogerio** [comment]
Do you have any example of this configuration?

**Comment by FezVrasta** [comment]
You need to define that in the Jest override function of react-app-rewired, you can read the project documentation for more info
